baseURL = "http://example.org/"
languageCode = "en-us"
title = "Hugo Blog"

[permalinks]
  blog = "/:filename/"

# See https://feathericons.com/
# The value of pre is the icon name
[menu]
  [[menu.main]]
    name = "Home"
    pre = "home"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "Blog"
    pre = "edit"
    url = "/blog/"
    weight = 2
  [[menu.main]]
    name = "About"
    pre = "eye"
    url = "/about/"
    weight = 3
  [[menu.main]]
    name = "Tags"
    pre = "tag"
    url = "/tags/"
    weight = 4
  [[menu.main]]
    name = "t"
    pre = "twitter"
    url = "https://twitter.com/ConstantDupuis"
    weight = 5
  [[menu.main]]
    name = "g"
    pre = "github"
    url = "https://github.com/MacFurax"
    weight = 6
  

[params]
  homeText = "You just made a Hugo blog from scratch."
